In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
list_array = [1, 2, 3]
a = list_array + list_array
print(a)

[1, 2, 3, 1, 2, 3]


In [15]:
numpy_array = np.array(list_array)
n = numpy_array + numpy_array
n

array([2, 4, 6])

In [19]:
list_matrix = [[1, 2, 3], [4, 5, 6]]
numpy_matrix = np.array(list_matrix)
print(numpy_matrix)

[[1 2 3]
 [4 5 6]]


In [26]:
# built-in functions

arranged_data = np.arange(0, 15, 3)
np_zeros = np.zeros(10)
np_ones = np.ones(10)

In [58]:
random_data = np.random.rand(100)*100
random_data = np.random.rand(5, 5)*100  # uniform distibution
random_data = np.random.randn(100)*0.2  # standard normal distrubition
random_data = np.random.randint(1, 100)


In [64]:
random_data = np.random.rand(5, 5)*100
random_data.shape
random_data.reshape(1, 25)

array([[ 0.48004606, 58.20125328, 65.61646856, 36.05944108, 55.01662595,
        71.24928164, 13.22686337, 31.88301469, 66.88184676, 16.70499362,
        22.6411336 , 21.98549442, 94.73062589, 20.3785561 , 43.93856807,
        20.58063929, 42.32503551, 86.22732468, 64.38671714, 58.41072703,
        13.01795583,  4.51210495, 57.80452073, 82.113836  ,  0.94768077]])

In [68]:
max_val = np.max(random_data)
min_val = np.min(random_data)
print(max_val)

94.73062588901429


In [79]:
data = np.loadtxt(r"winequality-red.csv", dtype='str', delimiter=';')
second_col = data[:,1]
plt.plot(data[:400, 3], data[:400, 3], 'o')
plt.xlabel('x_axis')
plt.ylabel('y_axis')
plt.title("Correlation")


In [84]:
data_to_save = data[100:400, 3:5]
np.savetxt('new.csv', data_to_save, delimiter=',', fmt='%s')